name: tf98
channels:
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - gensim
  - jupyter
  - nltk
  - pandas
  - python=3.9
  - sacremoses
  - scikit-learn
  - transformers
  - openpyxl
  - seaborn
  - matplotlib
  - pip:
      - pip==23
      - protobuf
      - tensorflow==2.10
